server {
    listen 80;

    # Serve os arquivos estáticos do seu site
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Encaminha chamadas de API para o Back-end Privado
    location /api/ {
        # Substitua pelo IP PRIVADO da sua instância de Back-end
        proxy_pass http://10.0.x.x:25000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
